-- database/aifya_schema.sql
-- Aifya Health Platform Database Schema
-- Requires PostgreSQL 16+

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: facility_config
-- Stores per-facility settings for multi-tenant deployments.
CREATE TABLE facility_config (
    facility_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    facility_name VARCHAR(255) NOT NULL,
    facility_level VARCHAR(50) NOT NULL,
    qafya_db_config JSONB, -- Stored encrypted if possible or accessed securely
    sha_facility_code VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: users
-- Core authentication and RBAC table. Emails are encrypted.
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email BYTEA NOT NULL, -- PII encrypted via pgcrypto
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('clinician', 'billing_admin', 'facility_admin', 'superadmin')),
    license_no VARCHAR(100), -- KMPDB registration (if clinician)
    is_active BOOLEAN DEFAULT TRUE,
    facility_id UUID REFERENCES facility_config(facility_id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: aifya_encounters
-- Enriched AI encounter layer linked to Q-Afya's base encounters.
CREATE TABLE aifya_encounters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    qafya_encounter_id VARCHAR(255) NOT NULL,
    qafya_patient_id VARCHAR(255) NOT NULL,
    facility_id UUID REFERENCES facility_config(facility_id),
    clinician_id UUID REFERENCES users(id),
    audio_file_ref VARCHAR(1024), -- Path in MinIO
    raw_transcript TEXT,
    diarized_transcript TEXT,
    soap_json JSONB,
    icd11_primary VARCHAR(50),
    icd11_secondary VARCHAR(50)[],
    confidence_scores JSONB,
    nlp_warnings TEXT[],
    admission_id VARCHAR(255), -- Used to group inpatient encounters
    encounter_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('in_progress', 'scribed', 'reviewed', 'finalized')),
    synced_to_qafya BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for aifya_encounters
CREATE INDEX idx_aifya_encounters_patient_id ON aifya_encounters(qafya_patient_id);
CREATE INDEX idx_aifya_encounters_admission_id ON aifya_encounters(admission_id);
CREATE INDEX idx_aifya_encounters_date ON aifya_encounters(encounter_date);

-- Table: claims
-- Tracks SHA claim lifecycle matching to encounters.
CREATE TABLE claims (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    encounter_id UUID REFERENCES aifya_encounters(id),
    facility_id UUID REFERENCES facility_config(facility_id),
    scrub_status VARCHAR(50) NOT NULL CHECK (scrub_status IN ('pending', 'passed', 'blocked', 'warnings_only', 'overridden')),
    scrub_violations JSONB,
    override_by UUID REFERENCES users(id),
    override_reason TEXT,
    override_at TIMESTAMPTZ,
    sha_submission_ref VARCHAR(255),
    claim_status VARCHAR(50) CHECK (claim_status IN ('submitted', 'under_review', 'approved', 'rejected', 'paid')),
    amount_billed NUMERIC(12, 2) NOT NULL,
    amount_approved NUMERIC(12, 2),
    amount_paid NUMERIC(12, 2),
    fhir_bundle JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for claims
CREATE INDEX idx_claims_encounter ON claims(encounter_id);
CREATE INDEX idx_claims_status ON claims(scrub_status);

-- Table: discharge_summaries
-- Structured discharge summaries generated by AI.
CREATE TABLE discharge_summaries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    admission_id VARCHAR(255) NOT NULL,
    patient_id VARCHAR(255) NOT NULL,
    facility_id UUID REFERENCES facility_config(facility_id),
    generating_clinician_id UUID REFERENCES users(id),
    admission_date TIMESTAMPTZ NOT NULL,
    discharge_date TIMESTAMPTZ NOT NULL,
    length_of_stay int NOT NULL,
    admission_diagnosis VARCHAR(255),
    final_diagnosis VARCHAR(255),
    icd11_code VARCHAR(50),
    clinical_narrative TEXT,
    procedures JSONB,
    key_investigations JSONB,
    discharge_meds JSONB,
    status VARCHAR(50) NOT NULL CHECK (status IN ('draft', 'reviewed', 'approved', 'sent_to_qafya')),
    reviewed_by UUID REFERENCES users(id),
    approved_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for discharge summaries
CREATE INDEX idx_discharge_admission ON discharge_summaries(admission_id);

-- Table: audit_log
-- Immutable audit trail for all critical actions including Q-Afya sync and claims override.
CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id),
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    details JSONB,
    ip_address INET,
    previous_hash BYTEA, -- Cryptographic hash of previous row for immutability
    row_hash BYTEA,      -- Cryptographic hash of current row
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rule to make audit log append-only (No Deletes or Updates allowed)
CREATE RULE audit_no_delete AS ON DELETE TO audit_log DO INSTEAD NOTHING;
CREATE RULE audit_no_update AS ON UPDATE TO audit_log DO INSTEAD NOTHING;

-- End of File
