export const IDENTITY_RULE_ID_TO_LOGIC_KEY = {
  'IDN-001': 'verify_patient_sha_id_exists',
  'IDN-002': 'verify_patient_sha_id_format',
  'IDN-003': 'verify_patient_eligibility_active',
  'IDN-004': 'verify_patient_name_matches_registry',
  'IDN-005': 'verify_national_id_present',
  'IDN-006': 'verify_patient_gender_consistent',
  'IDN-007': 'verify_patient_dob_consistent',
  'IDN-008': 'verify_facility_sha_code_valid',
  'IDN-009': 'verify_facility_tier_matches',
  'IDN-010': 'verify_practitioner_registered',
  'IDN-011': 'verify_practitioner_license_active',
  'IDN-012': 'verify_practitioner_specialty_appropriate',
  'IDN-013': 'verify_sha_card_copy_present',
  'IDN-014': 'verify_national_id_copy_legible',
  'IDN-015': 'verify_patient_contact_present',
} as const;

export const DOCUMENTATION_RULE_ID_TO_LOGIC_KEY = {
  'DOC-001': 'verify_claim_form_present',
  'DOC-002': 'verify_claim_form_type_matches',
  'DOC-003': 'verify_physician_signature_present',
  'DOC-004': 'verify_physician_stamp_present',
  'DOC-005': 'verify_claim_form_date_present',
  'DOC-006': 'verify_claim_form_date_matches_admission',
  'DOC-007': 'verify_discharge_summary_present_ip',
  'DOC-008': 'verify_discharge_summary_signed',
  'DOC-009': 'verify_physician_notes_present',
  'DOC-010': 'verify_diagnosis_documented_in_notes',
  'DOC-011': 'verify_treatment_plan_documented',
  'DOC-012': 'verify_lab_results_present_if_claimed',
  'DOC-013': 'verify_lab_results_from_accredited',
  'DOC-014': 'verify_prescription_present_if_pharmacy',
  'DOC-015': 'verify_prescription_signed',
  'DOC-016': 'verify_referral_letter_if_referred',
  'DOC-017': 'verify_referral_letter_valid',
  'DOC-018': 'verify_consent_form_if_surgical',
  'DOC-019': 'verify_consent_form_signed_by_patient',
  'DOC-020': 'verify_preauth_form_if_required',
  'DOC-021': 'verify_operative_note_if_surgical',
  'DOC-022': 'verify_anesthesia_record_if_applicable',
  'DOC-023': 'verify_nursing_notes_present_ip',
  'DOC-024': 'verify_radiology_report_if_claimed',
  'DOC-025': 'verify_all_pages_legible',
  'DOC-026': 'verify_no_critical_fields_missing',
  'DOC-027': 'verify_document_dates_consistent',
  'DOC-028': 'verify_patient_name_on_all_docs',
  'DOC-029': 'verify_facility_header_on_clinical_docs',
  'DOC-030': 'verify_maternity_delivery_record',
  'DOC-031': 'verify_baby_birth_notification',
  'DOC-032': 'verify_anc_card_if_maternity',
  'DOC-033': 'verify_document_not_expired',
  'DOC-034': 'verify_no_duplicate_documents',
  'DOC-035': 'verify_document_completeness_score',
} as const;

export const CLINICAL_RULE_ID_TO_LOGIC_KEY = {
  'CLN-001': 'verify_icd_code_valid',
  'CLN-002': 'verify_icd_code_specificity',
  'CLN-003': 'verify_diagnosis_matches_claim_type',
  'CLN-004': 'verify_procedure_matches_diagnosis',
  'CLN-005': 'verify_procedure_code_valid',
  'CLN-006': 'verify_los_appropriate',
  'CLN-007': 'verify_medications_match_diagnosis',
  'CLN-008': 'verify_lab_tests_relevant',
  'CLN-009': 'verify_no_clinical_contradictions',
  'CLN-010': 'verify_age_appropriate_diagnosis',
  'CLN-011': 'verify_gender_appropriate_diagnosis',
  'CLN-012': 'verify_maternity_gestational_age',
  'CLN-013': 'verify_vital_signs_documented',
  'CLN-014': 'verify_admission_criteria_met_ip',
  'CLN-015': 'verify_follow_up_plan_documented',
  'CLN-016': 'verify_emergency_triage_documented',
  'CLN-017': 'verify_allergy_documentation',
  'CLN-018': 'verify_dental_chart_if_dental',
  'CLN-019': 'verify_optical_prescription_if_optical',
  'CLN-020': 'verify_mental_health_assessment',
  'CLN-021': 'verify_dialysis_records_if_renal',
  'CLN-022': 'verify_bmi_documented',
  'CLN-023': 'verify_chronology_makes_sense',
  'CLN-024': 'verify_secondary_diagnosis_documented',
  'CLN-025': 'verify_clinical_completeness_score',
} as const;

export const AUTHORIZATION_RULE_ID_TO_LOGIC_KEY = {
  'AUT-001': 'verify_preauth_exists_if_required',
  'AUT-002': 'verify_preauth_number_valid',
  'AUT-003': 'verify_preauth_not_expired',
  'AUT-004': 'verify_preauth_covers_services',
  'AUT-005': 'verify_preauth_facility_matches',
  'AUT-006': 'verify_preauth_patient_matches',
  'AUT-007': 'verify_benefit_package_covers_service',
  'AUT-008': 'verify_referral_authorization',
  'AUT-009': 'verify_claim_within_7_day_window',
  'AUT-010': 'verify_no_duplicate_claim',
  'AUT-011': 'verify_copay_documented',
  'AUT-012': 'verify_emergency_retroauth',
  'AUT-013': 'verify_patient_coverage_active_at_service',
  'AUT-014': 'verify_referral_chain_complete',
  'AUT-015': 'verify_authorization_completeness_score',
} as const;

export const FINANCIAL_RULE_ID_TO_LOGIC_KEY = {
  'FIN-001': 'verify_tariff_code_exists',
  'FIN-002': 'verify_amount_within_tariff',
  'FIN-003': 'verify_tariff_tier_matches',
  'FIN-004': 'verify_quantity_reasonable',
  'FIN-005': 'verify_no_unbundling',
  'FIN-006': 'verify_no_upcoding',
  'FIN-007': 'verify_total_matches_lines',
  'FIN-008': 'verify_unit_price_consistent',
  'FIN-009': 'verify_pharmacy_items_formulary',
  'FIN-010': 'verify_los_charges_match_dates',
  'FIN-011': 'verify_consultation_fee_appropriate',
  'FIN-012': 'verify_surgical_fees_match_procedure',
  'FIN-013': 'verify_no_duplicate_line_items',
  'FIN-014': 'verify_maternity_package_rate',
  'FIN-015': 'verify_renal_session_rate',
  'FIN-016': 'verify_claim_total_within_expected_range',
  'FIN-017': 'verify_icu_charges_justified',
  'FIN-018': 'verify_implant_costs_documented',
  'FIN-019': 'verify_benefit_limit_not_exceeded',
  'FIN-020': 'verify_financial_completeness_score',
  'FIN-021': 'verify_hospital_approved_matches_claim',
} as const;

export const STRUCTURAL_RULE_ID_TO_LOGIC_KEY = {
  'STR-001': 'verify_claim_has_minimum_one_line',
  'STR-002': 'verify_claim_has_documents',
  'STR-003': 'verify_all_required_fields_present',
  'STR-004': 'verify_dates_logically_consistent',
  'STR-005': 'verify_line_item_numbering',
  'STR-006': 'verify_claim_not_duplicate',
  'STR-007': 'verify_extraction_completeness',
  'STR-008': 'verify_document_page_count_reasonable',
  'STR-009': 'verify_rulepack_integrity',
  'STR-010': 'verify_overall_claim_quality_score',
} as const;

export const RULE_ID_TO_LOGIC_KEY = {
  ...IDENTITY_RULE_ID_TO_LOGIC_KEY,
  ...DOCUMENTATION_RULE_ID_TO_LOGIC_KEY,
  ...CLINICAL_RULE_ID_TO_LOGIC_KEY,
  ...AUTHORIZATION_RULE_ID_TO_LOGIC_KEY,
  ...FINANCIAL_RULE_ID_TO_LOGIC_KEY,
  ...STRUCTURAL_RULE_ID_TO_LOGIC_KEY,
} as const;

export type SupportedRuleId = keyof typeof RULE_ID_TO_LOGIC_KEY;
