import uuid
from datetime import date, datetime

from sqlalchemy import Boolean, Date, DateTime, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.models.base import AuditMixin


class ReportTemplate(AuditMixin, Base):
    """
    Report template defining structure and parameters for generating reports.
    Covers MOH registers (705A/B, 710, 711, 717), departmental summaries,
    and custom facility reports.
    """

    __tablename__ = "report_templates"

    name: Mapped[str] = mapped_column(String(200), nullable=False)
    code: Mapped[str] = mapped_column(
        String(50), nullable=False, unique=True
    )  # e.g. MOH_705A, OPD_DAILY, PHARMACY_STOCK
    description: Mapped[str | None] = mapped_column(Text)

    # Classification
    category: Mapped[str] = mapped_column(
        String(30), default="operational", nullable=False
    )  # operational, clinical, financial, compliance, moh
    department: Mapped[str | None] = mapped_column(
        String(50)
    )  # opd, ipd, lab, pharmacy, radiology, mch, billing, all

    # Template
    report_type: Mapped[str] = mapped_column(
        String(20), default="tabular", nullable=False
    )  # tabular, chart, summary, register
    parameters_schema: Mapped[dict | None] = mapped_column(
        JSONB
    )  # JSON Schema for report input params
    query_config: Mapped[dict | None] = mapped_column(
        JSONB
    )  # Query configuration (tables, joins, aggregations)
    columns_config: Mapped[dict | None] = mapped_column(
        JSONB
    )  # Column definitions for tabular reports

    # Schedule
    is_scheduled: Mapped[bool] = mapped_column(default=False, nullable=False)
    schedule_cron: Mapped[str | None] = mapped_column(
        String(50)
    )  # Cron expression for auto-generation
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)

    # MOH specific
    moh_form_number: Mapped[str | None] = mapped_column(String(20))  # MOH 705A, MOH 710
    reporting_period: Mapped[str | None] = mapped_column(
        String(20)
    )  # daily, weekly, monthly, quarterly, annual


class GeneratedReport(AuditMixin, Base):
    """
    Generated report instance with cached results.
    Stores the output of running a report template with specific parameters.
    """

    __tablename__ = "generated_reports"

    template_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    report_number: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # RPT-YYYYMMDD-XXXX

    # Parameters used
    parameters: Mapped[dict | None] = mapped_column(JSONB)  # Input params snapshot
    date_from: Mapped[date] = mapped_column(Date, nullable=False)
    date_to: Mapped[date] = mapped_column(Date, nullable=False)

    # Results
    result_data: Mapped[dict | None] = mapped_column(JSONB)  # Report output data
    summary_data: Mapped[dict | None] = mapped_column(JSONB)  # Aggregated summary
    row_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Status
    status: Mapped[str] = mapped_column(
        String(20), default="generating", nullable=False
    )  # generating, completed, failed, expired

    # Output
    format: Mapped[str] = mapped_column(
        String(10), default="json", nullable=False
    )  # json, pdf, csv, xlsx
    file_key: Mapped[str | None] = mapped_column(
        String(500)
    )  # MinIO key for exported file

    # Generated by
    generated_by: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
